#!/bin/sh
# Re-embed files/dashboard.html into the job template after editing it.
# (base64 because the HTML's JS template literals `${...}` would clash
# with HCL heredoc interpolation — see homelab gotcha on $${} escaping.)
set -e
cd "$(dirname "$0")"
B64=$(base64 -i files/dashboard.html | tr -d '\n')
cat > templates/dashboard.nomad.tpl <<TPL
job "Dashboard" {
  datacenters = [[ var "datacenters" . | toStringList ]]
  type        = "service"

  group "dashboard-group" {
    count = 1

    network {
      mode = "bridge"
      port "http" {
        to = 80
      }
    }

    service {
      name = "dashboard"
      port = "http"
      tags = [[ var "service_tags" . | toStringList ]]

      # fabio only routes instances with a passing health check
      check {
        name     = "alive"
        type     = "http"
        path     = "/"
        interval = "15s"
        timeout  = "3s"
      }
    }

    task "server" {
      driver = "docker"

      config {
        image = "nginx:alpine"
        ports = ["http"]
        mounts = [
          {
            type   = "bind"
            source = "local/index.html"
            target = "/usr/share/nginx/html/index.html"
          },
          {
            type   = "bind"
            source = "secrets/default.conf"
            target = "/etc/nginx/conf.d/default.conf"
          }
        ]
      }

      # nginx config: static page + read-only miniflux proxy. The API key
      # is injected server-side here so it never reaches the browser.
      template {
        destination = "secrets/default.conf"
        change_mode = "restart"
        data        = <<EOH
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /api/miniflux/entries {
        limit_except GET { deny all; }
        proxy_pass [[ var "miniflux_upstream" . ]]/v1/entries;
        proxy_set_header X-Auth-Token "[[ var "miniflux_api_key" . ]]";
    }
}
EOH
      }

      # generated by update-html.sh from files/dashboard.html — do not edit
      template {
        destination = "local/index.html"
        change_mode = "restart"
        data        = <<EOH
{{ "$B64" | base64Decode }}
EOH
      }

      resources {
        cpu    = 100
        memory = 300
      }
    }
  }
}
TPL
echo "regenerated templates/dashboard.nomad.tpl ($(wc -c < templates/dashboard.nomad.tpl) bytes)"
